#!/usr/bin/env bash

TEMPDIR=/tmp
case "$(basename "$1" | tr '[A-Z]' '[a-z]')" in
  *.tar*)
    tar tf "$1"
  ;;
  *.zip)
    unzip -l "$1"
  ;;
  *.rar)
    unrar l "$1"
  ;;
  *.7z)
    7z l "$1"
  ;;
  *.avi|*.mp4|*.mkv)
    thumbnail="$TEMPDIR/thumbnail.png"
    ffmpeg -y -i "$1" -vframes 1 "$thumbnail"
    kitten icat --silent --stdin no --transfer-mode file --place "${2}x${3}@${4}x${5}" "$thumbnail" < /dev/null > /dev/tty
	;;
  *.pdf)
    thumbnail="$TEMPDIR/thumbnail.png"
    gs -o "$thumbnail" -sDEVICE=pngalpha -dLastPage=1 "$1" >/dev/null
    kitten icat --silent --stdin no --transfer-mode file --place "${2}x${3}@${4}x${5}" "$thumbnail" < /dev/null > /dev/tty
  ;;
  *.jpg|*.jpeg|*.png|*.bmp)
    imgcat "$1"
  ;;
  *.svg|*.webp)
    thumbnail="$TEMPDIR/thumbnail.png"
    convert "$1" "$thumbnail"
    kitten icat --silent --stdin no --transfer-mode file --place "${2}x${3}@${4}x${5}" "$thumbnail" < /dev/null > /dev/tty
	;;
  *)
    bat --force-colorization --paging=never --style=changes,numbers --terminal-width $(($2 - 3)) "$1"
  ;;
esac
