source ~/dotfiles/homefiles/aliases
source ~/Google\ Drive/My\ Drive/dotprivate/private

# FZF
# CTRL-/ to toggle small preview window to see the full command
# CTRL-Y to copy the command into clipboard using pbcopy
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPTS="
--reverse
--no-info
--pointer=' ' \
--marker=' ' \
--ansi \
--color='16,bg+:-1,gutter:-1,prompt:5,pointer:5,marker:6,border:4,label:4,header:italic'"
export FZF_TMUX_OPTS="-p 55%,60%"
export FZF_CTRL_R_OPTS="
  --border-label=' history '
  --prompt='  '
  --preview 'echo {}' --preview-window up:3:hidden:wrap
  --bind 'ctrl-/:toggle-preview'
  --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
  --color header:italic
  --header 'CTRL-Y copy command , CTRL-/ toggle preview'"

# Node version manager fnm
eval "$(fnm env --use-on-cd)"

# Zoxide
eval "$(zoxide init zsh)"

# exit vim mode with jj
bindkey -M viins 'jj' vi-cmd-mode

# Set go path
export GOPATH=~/.gocode

# Editor
export EDITOR=nvim
# Pager
export PAGER=bat

# PATH
export PATH="$PATH:$HOME/dotfiles/bin" # add local scripts to path
export PATH="$PATH:$HOME/Sites/awstools" # add local scripts to path
export PATH="/usr/local/bin:$PATH" # local before everything else
export PATH="$PATH:$HOME/.composer/vendor/bin" # add composer in path for global dependencies
export PATH="$PATH:$HOME/.rvm/bin" # add RVM to PATH for scripting
export PATH="$PATH:$HOME/.gocode/bin" # Add go scripts
export PATH=$HOME/.tmux/plugins/t-smart-tmux-session-manager/bin:$PATH #~/.tmux/plugins

# zsh autosuggestions
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
# zsh syntax highlight
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# zsh substring history
source /opt/homebrew/share/zsh-history-substring-search/zsh-history-substring-search.zsh
bindkey '^P' history-substring-search-up
bindkey '^N' history-substring-search-down

# history
setopt share_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_verify

# completion
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"

eval "$(starship init zsh)"

# bun completions
[ -s "/Users/aleksandar/.bun/_bun" ] && source "/Users/aleksandar/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# bat
export BAT_THEME="Catppuccin Macchiato"
