source ~/dotfiles/homefiles/aliases
source ~/My\ Drive/dotprivate/.private

# FZF
# CTRL-/ to toggle small preview window to see the full command
# CTRL-Y to copy the command into clipboard using pbcopy
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_CTRL_R_OPTS="
  --preview 'echo {}' --preview-window up:3:hidden:wrap
  --bind 'ctrl-/:toggle-preview'
  --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
  --color header:italic
  --header 'CTRL-Y copy command , CTRL-/ toggle preview'"

# Node version manager fnm
eval "$(fnm env --use-on-cd)"

# Zoxide
eval "$(zoxide init zsh)"

# Set go path
export GOPATH=~/.gocode

source /Users/gosevski/.config/broot/launcher/bash/br

# PATH
export PATH="$PATH:$HOME/dotfiles/bin" # add local scripts to path
export PATH="$PATH:$HOME/Sites/awstools" # add local scripts to path
export PATH="/usr/local/bin:$PATH" # local before everything else
export PATH="$PATH:$HOME/.composer/vendor/bin" # add composer in path for global dependencies
export PATH="$PATH:$HOME/.rvm/bin" # add RVM to PATH for scripting
export PATH="$PATH:$HOME/.gocode/bin" # Add go scripts
export PATH=$HOME/.tmux/plugins/t-smart-tmux-session-manager/bin:$PATH #~/.tmux/plugins

eval "$(starship init zsh)"
